fixtures:
    symlinks:
      openbgpd: "#{source_dir}"
    repositories:
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
        ref: 4.12.0
      tea:
        repo: https://github.com/icann-dns/puppet-tea.git
        ref: 0.2.2
