stages:
  - rspec
  - rubocop
  - beaker_apply
  - beaker_agent

before_script:
  - ruby -v
  - bundle --version
  - gem --version
  - rvm use 2.3  - rm Gemfile.lock || true
  - FACTER_GEM_VERSION="< 2.5" bundle install --path=${BUNDLE_PATH:-vendor/bundle}

rspec:
  stage: rspec
  variables:
    FACTER_GEM_VERSION: '< 2.5'
  script:
    - bundle exec rake test

rubocop:
  stage: rubocop
  script:
    - bundle exec rake rubocop

beaker:
  stage: beaker_apply
  variables:
    BEAKER_set: freebsd-multi-10.3
    BEAKER_TESTMODE: apply
  script:
    -  bundle exec rake beaker
