stages:
  - rspec
  - rubocop
  - beaker_apply
  - beaker_agent

before_script:
  - rvm -v
  - ruby -v
  - bundle --version
  - gem --version
  - rvm use 2.3
  - rm Gemfile.lock || true
  - bundle install

rspec:
  stage: rspec
  script:
    - bundle exec rake test

rubocop:
  stage: rubocop
  script:
    - bundle exec rake rubocop

beaker:
  stage: beaker_apply
  variables:
    BEAKER_set: freebsd-multi-10.3
    BEAKER_TESTMODE: apply
  script:
    -  bundle exec rake beaker
