require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.3
  Include:
    - ./**/*.rb
  Exclude:
    - files/**/*
    - vendor/**/*
    - .vendor/**/*
    - pkg/**/*
    - spec/fixtures/**/*
    - Gemfile
    - Vagrantfile
    - Rakefile
    - Guardfile
Lint/ConditionPosition:
  Enabled: True

Lint/ElseLayout:
  Enabled: True

Lint/UnreachableCode:
  Enabled: True

Lint/UselessComparison:
  Enabled: True

Lint/EnsureReturn:
  Enabled: True

Lint/HandleExceptions:
  Enabled: True

Lint/LiteralInCondition:
  Enabled: True

Lint/ShadowingOuterLocalVariable:
  Enabled: True

Lint/LiteralInInterpolation:
  Enabled: True

Layout/IndentHeredoc:
  Enabled: False

Layout/HashSyntax:
  Enabled: True

Layout/RedundantReturn:
  Enabled: True

Lint/AmbiguousOperator:
  Enabled: True

Lint/AssignmentInCondition:
  Enabled: True

Layout/SpaceBeforeComment:
  Enabled: True

Layout/AndOr:
  Enabled: True

Layout/RedundantSelf:
  Enabled: True

Metrics/BlockLength:
  Enabled: False

# Method length is not necessarily an indicator of code quality
Metrics/MethodLength:
  Enabled: False

# Module length is not necessarily an indicator of code quality
Metrics/ModuleLength:
  Enabled: False

Layout/WhileUntilModifier:
  Enabled: True

Lint/AmbiguousRegexpLiteral:
  Enabled: True

Security/Eval:
  Enabled: True

Lint/BlockAlignment:
  Enabled: True

Lint/DefEndAlignment:
  Enabled: True

Lint/EndAlignment:
  Enabled: True

Lint/DeprecatedClassMethods:
  Enabled: True

Lint/Loop:
  Enabled: True

Lint/ParenthesesAsGroupedExpression:
  Enabled: True

Lint/RescueException:
  Enabled: True

Lint/StringConversionInInterpolation:
  Enabled: True

Lint/UnusedBlockArgument:
  Enabled: True

Lint/UnusedMethodArgument:
  Enabled: True

Lint/UselessAccessModifier:
  Enabled: True

Lint/UselessAssignment:
  Enabled: True

Lint/Void:
  Enabled: True

Layout/AccessModifierIndentation:
  Enabled: True

Layout/AccessorMethodName:
  Enabled: True

Layout/Alias:
  Enabled: True

Layout/AlignArray:
  Enabled: True

Layout/AlignHash:
  Enabled: True

Layout/AlignParameters:
  Enabled: True

Metrics/BlockNesting:
  Enabled: True

Layout/AsciiComments:
  Enabled: True

Layout/Attr:
  Enabled: True

Layout/BracesAroundHashParameters:
  Enabled: True

Layout/CaseEquality:
  Enabled: True

Layout/CaseIndentation:
  Enabled: True

Layout/CharacterLiteral:
  Enabled: True

Layout/ClassAndModuleCamelCase:
  Enabled: True

Layout/ClassAndModuleChildren:
  Enabled: False

Layout/ClassCheck:
  Enabled: True

# Class length is not necessarily an indicator of code quality
Metrics/ClassLength:
  Enabled: False

Layout/ClassMethods:
  Enabled: True

Layout/ClassVars:
  Enabled: True

Layout/WhenThen:
  Enabled: True

Layout/WordArray:
  Enabled: True

Layout/UnneededPercentQ:
  Enabled: True

Layout/Tab:
  Enabled: True

Layout/SpaceBeforeSemicolon:
  Enabled: True

Layout/TrailingBlankLines:
  Enabled: True

Layout/SpaceInsideBlockBraces:
  Enabled: True

Layout/SpaceInsideBrackets:
  Enabled: True

Layout/SpaceInsideHashLiteralBraces:
  Enabled: True

Layout/SpaceInsideParens:
  Enabled: True

Layout/LeadingCommentSpace:
  Enabled: True

Layout/SpaceAfterColon:
  Enabled: True

Layout/SpaceAfterComma:
  Enabled: True

Layout/SpaceAfterMethodName:
  Enabled: True

Layout/SpaceAfterNot:
  Enabled: True

Layout/SpaceAfterSemicolon:
  Enabled: True

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: True

Layout/SpaceAroundOperators:
  Enabled: True

Layout/SpaceBeforeBlockBraces:
  Enabled: True

Layout/SpaceBeforeComma:
  Enabled: True

Layout/CollectionMethods:
  Enabled: True

Layout/CommentIndentation:
  Enabled: True

Layout/ColonMethodCall:
  Enabled: True

Layout/CommentAnnotation:
  Enabled: True

# 'Complexity' is very relative
Metrics/CyclomaticComplexity:
  Enabled: False

Layout/ConstantName:
  Enabled: True

Layout/Documentation:
  Enabled: False

Layout/DefWithParentheses:
  Enabled: True

Layout/PreferredHashMethods:
  Enabled: True

Layout/DotPosition:
  EnforcedLayout: trailing

Layout/DoubleNegation:
  Enabled: True

Layout/EachWithObject:
  Enabled: True

Layout/EmptyLineBetweenDefs:
  Enabled: True

Layout/IndentArray:
  Enabled: True

Layout/IndentHash:
  Enabled: True

Layout/IndentationConsistency:
  Enabled: True

Layout/IndentationWidth:
  Enabled: True

Layout/EmptyLines:
  Enabled: True

Layout/EmptyLinesAroundAccessModifier:
  Enabled: True

Layout/EmptyLiteral:
  Enabled: True

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Enabled: False

Layout/MethodCallWithoutArgsParentheses:
  Enabled: True

Layout/MethodDefParentheses:
  Enabled: True

Layout/LineEndConcatenation:
  Enabled: True

Layout/TrailingWhitespace:
  Enabled: True

Layout/StringLiterals:
  Enabled: True

Layout/TrailingCommaInArguments:
  Enabled: True

Layout/TrailingCommaInLiteral:
  Enabled: True

Layout/GlobalVars:
  Enabled: True

Layout/GuardClause:
  Enabled: True

Layout/IfUnlessModifier:
  Enabled: True

Layout/MultilineIfThen:
  Enabled: True

Layout/NegatedIf:
  Enabled: True

Layout/NegatedWhile:
  Enabled: True

Layout/Next:
  Enabled: True

Layout/SingleLineBlockParams:
  Enabled: True

Layout/SingleLineMethods:
  Enabled: True

Layout/SpecialGlobalVars:
  Enabled: True

Layout/TrivialAccessors:
  Enabled: True

Layout/UnlessElse:
  Enabled: True

Layout/VariableInterpolation:
  Enabled: True

Layout/VariableName:
  Enabled: True

Layout/WhileUntilDo:
  Enabled: True

Layout/EvenOdd:
  Enabled: True

Layout/FileName:
  Enabled: True

Layout/For:
  Enabled: True

Layout/Lambda:
  Enabled: True

Layout/MethodName:
  Enabled: True

Layout/MultilineTernaryOperator:
  Enabled: True

Layout/NestedTernaryOperator:
  Enabled: True

Layout/NilComparison:
  Enabled: True

Layout/FormatString:
  Enabled: True

Layout/MultilineBlockChain:
  Enabled: True

Layout/Semicolon:
  Enabled: True

Layout/SignalException:
  Enabled: True

Layout/NonNilCheck:
  Enabled: True

Layout/Not:
  Enabled: True

Layout/NumericLiterals:
  Enabled: True

Layout/OneLineConditional:
  Enabled: True

Layout/OpMethod:
  Enabled: True

Layout/ParenthesesAroundCondition:
  Enabled: True

Layout/PercentLiteralDelimiters:
  Enabled: True

Layout/PerlBackrefs:
  Enabled: True

Layout/PredicateName:
  Enabled: True

Layout/RedundantException:
  Enabled: True

Layout/SelfAssignment:
  Enabled: True

Layout/Proc:
  Enabled: True

Layout/RaiseArgs:
  Enabled: True

Layout/RedundantBegin:
  Enabled: True

Layout/RescueModifier:
  Enabled: True

# based on https://github.com/voxpupuli/modulesync_config/issues/168
Layout/RegexpLiteral:
  EnforcedLayout: percent_r
  Enabled: True

Lint/UnderscorePrefixedVariableName:
  Enabled: True

Metrics/ParameterLists:
  Enabled: False

Lint/RequireParentheses:
  Enabled: True

Layout/SpaceBeforeFirstArg:
  Enabled: True

Layout/ModuleFunction:
  Enabled: True

Lint/Debugger:
  Enabled: True

Layout/IfWithSemicolon:
  Enabled: True

Layout/Encoding:
  Enabled: True

Layout/BlockDelimiters:
  Enabled: True

Layout/MultilineBlockLayout:
  Enabled: True

# 'Complexity' is very relative
Metrics/AbcSize:
  Enabled: False

# 'Complexity' is very relative
Metrics/PerceivedComplexity:
  Enabled: False

Lint/UselessAssignment:
  Enabled: True

Layout/ClosingParenthesisIndentation:
  Enabled: True

# RSpec

RSpec/BeforeAfterAll:
  Exclude:
    - spec/acceptance/**/*

# We don't use rspec in this way
RSpec/DescribeClass:
  Enabled: False

# Example length is not necessarily an indicator of code quality
RSpec/ExampleLength:
  Enabled: False

RSpec/NamedSubject:
  Enabled: False

# disabled for now since they cause a lot of issues
# these issues aren't easy to fix
RSpec/RepeatedDescription:
  Enabled: False

RSpec/NestedGroups:
  Enabled: False

# this is broken on ruby1.9
Layout/IndentHeredoc:
  Enabled: False

# disable Yaml safe_load. This is needed to support ruby2.0.0 development envs
Security/YAMLLoad:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false
